version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: task_db
    environment:
      MYSQL_DATABASE: taskmanager
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - task_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/taskmanager?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysqldb
    networks:
      - task_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - task_network

volumes:
  mysql_data:

networks:
  task_network:
    driver: bridge